In [2]:
# crispdm >> cross industry standard process for data mining
# NUMPY >> Numerical Python

In [4]:
import numpy as np
import random

In [6]:
np.__version__

'1.26.4'

In [16]:
l = [1,2,3,4,5]
arr = np.array(l)

In [10]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr.ndim # to know the dimension of array

1

In [18]:
l1 = [1,2,3,4,5]
np.asarray(l1) # directly convert to an array even if is an array or not an array
# np.asanyarray converts the input to an ndarray, but pass ndarray subclasses through i.e.
# if input is a matrix or any other subclass, it will not be converted to array

array([1, 2, 3, 4, 5])

In [ ]:
# matrix is a specialised 2D array (always 2D)
# 

In [22]:
# Other ways of creating array
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
# 1. 
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
# 2.
it = (i for i in range(5))
np.fromiter(it,int)

array([0, 1, 2, 3, 4])

In [28]:
# 3.
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 4.
np.linspace(1, 5, 10) # Return evenly spaced numbers over a specified interval
# Give me 10 numbers between 1 and 5 evenly spaced.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
# Advance numpy
a = np.zeros((2,3)) # 2-D

In [48]:
a.ndim

2

In [54]:
b = np.zeros((1,2,3)) # 3-D
b

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [52]:
b.ndim

3

In [58]:
np.eye(3, dtype = int) # returns a 2-D array with ones in the diagonal and zeros elsewhere

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [2]:
# while reshaping number of elements must be same

In [8]:
# conditions on array
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[9, 8, 8, 1, 5, 8],
       [8, 6, 7, 4, 6, 7],
       [3, 8, 1, 7, 9, 2],
       [9, 6, 1, 3, 9, 1],
       [1, 6, 3, 2, 9, 1]])

In [12]:
arr1>3  # returns true for the values that are greater than 3

array([[ True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True, False],
       [ True,  True, False, False,  True, False],
       [False,  True, False, False,  True, False]])

In [14]:
arr1[arr1>3] # returns elements that are greater than 3

array([9, 8, 8, 5, 8, 8, 6, 7, 4, 6, 7, 8, 7, 9, 9, 6, 9, 6, 9])

In [16]:
# to access elements
arr1[0] # returns 0th row

array([9, 8, 8, 1, 5, 8])

In [20]:
arr1[1][3] # returns 1st row 3rd element

4

In [22]:
arr1[0:2] # returns 0th row and 1st row, similar to string slicing

array([[9, 8, 8, 1, 5, 8],
       [8, 6, 7, 4, 6, 7]])

In [24]:
arr1[0:2,[0,2]] # [0,2] returns 0th and 2nd column

array([[9, 8],
       [8, 7]])

In [26]:
arr1[0:2,0:2] # 1st and 2nd row and column

array([[9, 8],
       [8, 6]])

In [28]:
# transpose
arr1.T

array([[9, 8, 3, 9, 1],
       [8, 6, 8, 6, 6],
       [8, 7, 1, 1, 3],
       [1, 4, 7, 3, 2],
       [5, 6, 9, 9, 9],
       [8, 7, 2, 1, 1]])

In [30]:
np.sqrt(arr1)

array([[3.        , 2.82842712, 2.82842712, 1.        , 2.23606798,
        2.82842712],
       [2.82842712, 2.44948974, 2.64575131, 2.        , 2.44948974,
        2.64575131],
       [1.73205081, 2.82842712, 1.        , 2.64575131, 3.        ,
        1.41421356],
       [3.        , 2.44948974, 1.        , 1.73205081, 3.        ,
        1.        ],
       [1.        , 2.44948974, 1.73205081, 1.41421356, 3.        ,
        1.        ]])

In [32]:
np.log10(arr1)

array([[0.95424251, 0.90308999, 0.90308999, 0.        , 0.69897   ,
        0.90308999],
       [0.90308999, 0.77815125, 0.84509804, 0.60205999, 0.77815125,
        0.84509804],
       [0.47712125, 0.90308999, 0.        , 0.84509804, 0.95424251,
        0.30103   ],
       [0.95424251, 0.77815125, 0.        , 0.47712125, 0.95424251,
        0.        ],
       [0.        , 0.77815125, 0.47712125, 0.30103   , 0.95424251,
        0.        ]])

In [34]:
np.exp(arr1) # exponential

array([[8.10308393e+03, 2.98095799e+03, 2.98095799e+03, 2.71828183e+00,
        1.48413159e+02, 2.98095799e+03],
       [2.98095799e+03, 4.03428793e+02, 1.09663316e+03, 5.45981500e+01,
        4.03428793e+02, 1.09663316e+03],
       [2.00855369e+01, 2.98095799e+03, 2.71828183e+00, 1.09663316e+03,
        8.10308393e+03, 7.38905610e+00],
       [8.10308393e+03, 4.03428793e+02, 2.71828183e+00, 2.00855369e+01,
        8.10308393e+03, 2.71828183e+00],
       [2.71828183e+00, 4.03428793e+02, 2.00855369e+01, 7.38905610e+00,
        8.10308393e+03, 2.71828183e+00]])

In [36]:
np.min(arr1)

1

In [38]:
np.max(arr1)

9

In [56]:
arr2 = np.random.randint(1,3,(3,3))
arr2

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [64]:
arr2.flatten() # collapses all values into 1D

array([2, 1, 1, 2, 2, 1, 1, 2, 1])

In [70]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [72]:
np.squeeze(a) #Remove axes of length one from array i.e 2D converted to 1D

array([1, 2, 3])

In [66]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [68]:
np.roll(a, -2) # for rolling 2-D array provide axis = 0 or 1

array([[3],
       [1],
       [2]])

In [78]:
np.power(arr2, 3)

array([[8, 1, 1],
       [8, 8, 1],
       [1, 8, 1]], dtype=int32)

In [80]:
np.mean(arr2)

1.4444444444444444

In [82]:
np.std(arr2)

0.4969039949999533

In [84]:
np.var(arr2)

0.2469135802469136

In [88]:
# sort search in numpy array
b = np.array([5,3,4,1,2])
b

array([5, 3, 4, 1, 2])

In [90]:
np.sort(b)

array([1, 2, 3, 4, 5])

In [112]:
c = np.array([4,34,567,123,50,7,81])
c

array([  4,  34, 567, 123,  50,   7,  81])

In [118]:
d = np.sort(c)
d

array([  4,   7,  34,  50,  81, 123, 567])

In [122]:
np.searchsorted(d,45) #Find indices where elements should be inserted to maintain order.
# only sorted array must be passed.

3

In [124]:
np.count_nonzero(c) # or c[c>0]

7

In [126]:
np.linalg.det(arr2)

0.9999999999999998

In [134]:
np.linalg.inv(arr2)

array([[-1.11022302e-16,  1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 2.00000000e+00, -3.00000000e+00,  2.00000000e+00]])

In [138]:
# solving linear equations in numpy
a = np.array([[7,5.3,-3],[2,-5,2],[5,3,-7]])

In [140]:
b = np.array([16,8,0])

In [142]:
np.linalg.solve(a,b) # returns the values x, y, z

array([2.90387858, 0.47217538, 2.27655987])

In [ ]:
# PANDAS
# df.info